version: "3"
services:
  bookstack:
    image: linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - DB_HOST=bookstack_db
      - DB_USER=db_user
      - DB_PASS=passwd
      - DB_DATABASE=bookstackapp
      - APP_URL=https://archives.stefanshome.ca
    volumes:
      - /home/bookstack/config:/config
    restart: unless-stopped
    depends_on:
      - bookstack_db
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bookstack.entrypoints=http"
      - "traefik.http.routers.bookstack.rule=Host(`bookstack.yourwebsite.ca`)"
      - "traefik.http.middlewares.bookstack-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.bookstack.middlewares=bookstack-https-redirect"
      - "traefik.http.routers.bookstack-secure.entrypoints=https"
      - "traefik.http.routers.bookstack-secure.rule=Host(`bookstack.yourwebsite.ca`)"
      - "traefik.http.routers.bookstack-secure.service=bookstack"
      - "traefik.http.routers.bookstack-secure.tls=true"
      - "traefik.http.services.bookstack.loadBalancer.server.port=80"
      - "traefik.docker.network=proxy"
 
  bookstack_db:
    image: linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=P@55w0rd
      - TZ=America/Toronto
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=passwd
    volumes:
      - /home/bookstack/config:/config
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.db.rule=HostSNI(`*`)"
      - "traefik.tcp.services.db.loadbalancer.server.port=3306"
      - "traefik.tcp.routers.db.entrypoints=mysql"
      
networks:
  proxy:
    external:
      name: proxy